--- #YAML:1.0
name: Template-Plugin-Pageset
version: 1.01
author:
  - Chunzi <me@chunzi.org>
abstract: wrapper for Data::Page::Pageset
license: perl
generated_by: Module::Build version 0.26, without YAML.pm
